version: '3.7'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/test
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
  db:
    image: postgres
    environment:
      DB_NAME: test
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_HOST: postgres://postgres:admin@db:5432/test
    volumes:
      - ./pgdata:/var/lib/postgresql/data

    ports:
      - '5432:5432'
